name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking and local storage
  http: ^1.2.0
  shared_preferences: ^2.5.5

  # UI
  shimmer: ^3.0.0
  intl: ^0.20.2

  # Images
  image_picker: ^1.2.2
  image_cropper: ^11.0.0

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true